apiVersion: v1 
kind: PersistentVolumeClaim 
metadata: 
  name: pvc-school 
  labels: 
    apps: pvc-school 
  namespace: webserver 
spec: 
  accessModes: 
    - ReadWriteMany 
  resources: 
    requests: 
      storage: '1Gi'
  storageClassName: longhorn 