apiVersion: networking.k8s.io/v1 
kind: Ingress 
metadata: 
  name: school-url 
  namespace: webserver 
spec: 
  ingressClassName: nginx 
  rules: 
    - host: 'school.mydomain.com.br'
      http:
        paths: 
          - path: /
            pathType: Prefix 
            backend: 
              service: 
                name: school-svc
                port:
                  number: 3000